### ISSUE TITLE
Emoticons size

### ISSUE THREAD

**Issue by toinouu** [helios-ag/FMBbCodeBundle#105]
Hi !

I'd use emoticons https://github.com/twitter/twemoji 
But sizes do not correspond with the size I want.

I would like to force size to 20px

It's possible to add the ability to give a default size for emoticons?

Thx !

**Comment by alquerci** [comment]
You can play with the emoticon [configuration field][0] `html` and `xhtml`.

[0]: https://github.com/helios-ag/FMBbCodeBundle#customize-your-own-emoticons

**Comment by toinouu** [comment]
ok :) 

Thx !
