### ISSUE TITLE
bbcode_clean escape all HTML

### ISSUE THREAD

**Issue by tom10271** [helios-ag/FMBbCodeBundle#111]
{{ post.text | bbcode_filter('forum') | bbcode_clean | raw }}

It parse bbcode and clear other bbcode I don't want to support yet it returns plain HTML as text

**Comment by helios-ag** [comment]
I'm not sure that understand you,
if i'm not right, correct me. So you want to strip bbcode, that not allowed in your configuration?
Because this bundle based on decoda, i'm not sure that's possible.

**Comment by alquerci** [comment]
Hi @tom10271 

It's possible to do what you want. Simply create a `filter_set` with `escaping: false` and use it for cleaning like `bbcode_filter('forum')`. It's not tested but it should do what you want.

**Comment by helios-ag** [comment]
closed due to inactivity
