### ISSUE TITLE
[broken] post-install-cmd and post-update-cmd wrong parameters

### ISSUE THREAD

**Issue by sebastienvermeille** [helios-ag/FMBbCodeBundle#112]
After I added this line in post-install-cmd and post-update-cmd : 
"FM\\BbcodeBundle\\Composer\\ScriptHandler::installEmoticons"

I get this error : 
 [ErrorException]
  Argument 1 passed to Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::getOptions() must be an instance of Composer\Script\CommandEvent, instance of Composer\Script\Event given, called in ...\vendor\helios-ag\fm-bbcode-bundle\Composer\ScriptHandler.php on line 16 and defined

**Comment by helios-ag** [comment]
Fixed in #114
