### ISSUE TITLE
Only the first emoticon of the message is converted

### ISSUE THREAD

**Issue by sebastienvermeille** [helios-ag/FMBbCodeBundle#113]
Hello,
I have a problem with your bundle. Everything works fine except emoticons. 

I added "hooks: [ emoticon ]" in my config and it converts only my smiley if there is only one in the message : http://hpics.li/214be2e

Here is my emoticons.yml : 
https://gist.github.com/sebastienvermeille/5d9a2b90dff4844532d7

It is really strange... could you give me an advice if you think this is something I did wrong ? Thank you in advance

**Comment by helios-ag** [comment]
Hi @sebastienvermeille 
I've reproduced your emoticons.yml, and everything looks fine, take a look at this gist to check other options: https://gist.github.com/helios-ag/614ad58ea1619d22581c

**Comment by sebastienvermeille** [comment]
Hi @helios-ag I'll have a look on it tomorrow morning thank you very much ! And I saw you published a fix for the post-install cmd thank you too for that ;)
