### ISSUE TITLE
How to use the template option ?

### ISSUE THREAD

**Issue by QuozPowa** [helios-ag/FMBbCodeBundle#123]
Hello everyone, I don't know if I'm posting this message in the right place...
But I would like to know how to use the template option in the config.yml file.
For example, I would like to overwrite the video.php template provided by decoda and we have only the ability to add a template file according to the documentation. I think some options are missing.
Any help would be appreciated !

**Comment by helios-ag** [comment]
As you can see on https://github.com/helios-ag/FMBbCodeBundle/blob/master/DependencyInjection/Configuration.php#L68
there is a path option, which accepts path to template, that can be set with option something like: "%kernel.root_dir%\<template_path.php>"

**Comment by QuozPowa** [comment]
Thanks for your quick answer ! Is it possible to override an existing template and is it possible to link template and tag ? I tried to add a template path with "video.php" name like that : 
fm_bbcode:
    config:
      templates:
        - path: @PlatformBundle/Resources/views/templates/video.php

But it doesn't seem to overwrite the existing one.

**Comment by QuozPowa** [comment]
Ok, I found a lot of information in the decoda doc. I think I will get it !
