### ISSUE TITLE
List of availableBBCodes

### ISSUE THREAD

**Issue by MatthAddax** [helios-ag/FMBbCodeBundle#131]
Hi,

I would like to see the list of all available BBCodes.Where are they located?
Can anyone tell, I looked for them in the repository but didn't find anything.

Thanks for your help :)

**Comment by helios-ag** [comment]
Check decoda [repo](https://github.com/milesj/decoda/blob/master/readme.md#filters)

**Comment by MatthAddax** [comment]
Thanks :+1: I missed it when searching yesterday :)

**Comment by helios-ag** [comment]
Closing it as resolved.
