### ISSUE TITLE
The list aren't working.

### ISSUE THREAD

**Issue by PierreAdam** [helios-ag/FMBbCodeBundle#71]
Hello,

I tried to use that with the filter ```list```

```
[list]
[*] Element 1
[*] Element 2
[/list]
```

**Comment by alquerci** [comment]
That feature was added since Decoda 6.2.0 and you can look at this [test case][0] who it works.

[0]: https://github.com/milesj/decoda/blob/729dc63b63ca2fa949ec49645b670806eebae542/tests/Decoda/Filter/ListFilterTest.php#L78

**Comment by helios-ag** [comment]
I confirm this bug. This behavior due to uppercase'd check List filter definition in decoda https://github.com/milesj/decoda/blob/master/src/Decoda/Decoda.php#L1295

**Comment by helios-ag** [comment]
Fixed in #103
